[package]
name = "hope"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
futures = "0.3.28"
reqwest = "0.11.20"
scraper = "0.17.1"
tokio = { version = "1.32.0", features = ["full"] }
vader_sentiment = { git = "https://github.com/ckw017/vader-sentiment-rust" }
